import { User } from "./user";

export class Repository {
  id: number | undefined;
  node_id: string | undefined;
  name: string | undefined;
  full_name: string | undefined;
  private: boolean | undefined;
  owner: User | undefined;
  html_url: string | undefined;
  description: string | undefined;
  url: string | undefined;
  created_at: Date | undefined;
  updated_at: Date | undefined;
  stargazers_count: number = 0;
  watchers_count: number = 0;
}

// "forks_url":
// "keys_url": "https://api.github.com/repos/renan/ansible/keys{/key_id}",
// "collaborators_url": "https://api.github.com/repos/renan/ansible/collaborators{/collaborator}",
// "teams_url": "https://api.github.com/repos/renan/ansible/teams",
// "hooks_url": "https://api.github.com/repos/renan/ansible/hooks",
// "issue_events_url": "https://api.github.com/repos/renan/ansible/issues/events{/number}",
// "events_url": "https://api.github.com/repos/renan/ansible/events",
// "assignees_url": "https://api.github.com/repos/renan/ansible/assignees{/user}",
// "branches_url": "https://api.github.com/repos/renan/ansible/branches{/branch}",
// "tags_url": "https://api.github.com/repos/renan/ansible/tags",
// "blobs_url": "https://api.github.com/repos/renan/ansible/git/blobs{/sha}",
// "git_tags_url": "https://api.github.com/repos/renan/ansible/git/tags{/sha}",
// "git_refs_url": "https://api.github.com/repos/renan/ansible/git/refs{/sha}",
// "trees_url": "https://api.github.com/repos/renan/ansible/git/trees{/sha}",
// "statuses_url": "https://api.github.com/repos/renan/ansible/statuses/{sha}",
// "languages_url": "https://api.github.com/repos/renan/ansible/languages",
// "stargazers_url": "https://api.github.com/repos/renan/ansible/stargazers",
// "contributors_url": "https://api.github.com/repos/renan/ansible/contributors",
// "subscribers_url": "https://api.github.com/repos/renan/ansible/subscribers",
// "subscription_url": "https://api.github.com/repos/renan/ansible/subscription",
// "commits_url": "https://api.github.com/repos/renan/ansible/commits{/sha}",
// "git_commits_url": "https://api.github.com/repos/renan/ansible/git/commits{/sha}",
// "comments_url": "https://api.github.com/repos/renan/ansible/comments{/number}",
// "issue_comment_url": "https://api.github.com/repos/renan/ansible/issues/comments{/number}",
// "contents_url": "https://api.github.com/repos/renan/ansible/contents/{+path}",
// "compare_url": "https://api.github.com/repos/renan/ansible/compare/{base}...{head}",
// "merges_url": "https://api.github.com/repos/renan/ansible/merges",
// "archive_url": "https://api.github.com/repos/renan/ansible/{archive_format}{/ref}",
// "downloads_url": "https://api.github.com/repos/renan/ansible/downloads",
// "issues_url": "https://api.github.com/repos/renan/ansible/issues{/number}",
// "pulls_url": "https://api.github.com/repos/renan/ansible/pulls{/number}",
// "milestones_url": "https://api.github.com/repos/renan/ansible/milestones{/number}",
// "notifications_url": "https://api.github.com/repos/renan/ansible/notifications{?since,all,participating}",
// "labels_url": "https://api.github.com/repos/renan/ansible/labels{/name}",
// "releases_url": "https://api.github.com/repos/renan/ansible/releases{/id}",
// "deployments_url": "https://api.github.com/repos/renan/ansible/deployments",
// "created_at": "2017-12-20T21:20:56Z",
// "updated_at": "2021-03-26T15:19:42Z",
// "pushed_at": "2017-12-20T21:17:58Z",
// "git_url": "git://github.com/renan/ansible.git",
// "ssh_url": "git@github.com:renan/ansible.git",
// "clone_url": "https://github.com/renan/ansible.git",
// "svn_url": "https://github.com/renan/ansible",
// "homepage": "https://www.ansible.com/",
// "size": 102470,
// "stargazers_count": 0,
// "watchers_count": 0,
// "language": "Python",
// "has_issues": false,
// "has_projects": true,
// "has_downloads": true,
// "has_wiki": false,
// "has_pages": false,
// "has_discussions": false,
// "forks_count": 0,
// "mirror_url": null,
// "archived": false,
// "disabled": false,
// "open_issues_count": 0,
// "license": {
//   "key": "gpl-3.0",
//   "name": "GNU General Public License v3.0",
//   "spdx_id": "GPL-3.0",
//   "url": "https://api.github.com/licenses/gpl-3.0",
//   "node_id": "MDc6TGljZW5zZTk="
// },
// "allow_forking": true,
// "is_template": false,
// "web_commit_signoff_required": false,
// "topics": [

// ],
// "visibility": "public",
// "forks": 0,
// "open_issues": 0,
// "watchers": 0,
// "default_branch": "devel"
// },
// {
// "id": 28665265,
// "node_id": "MDEwOlJlcG9zaXRvcnkyODY2NTI2NQ==",
// "name": "assert",
// "full_name": "renan/assert",
// "private": false,
// "owner": {
//   "login": "renan",
//   "id": 28046,
//   "node_id": "MDQ6VXNlcjI4MDQ2",
//   "avatar_url": "https://avatars.githubusercontent.com/u/28046?v=4",
//   "gravatar_id": "",
//   "url": "https://api.github.com/users/renan",
//   "html_url": "https://github.com/renan",
//   "followers_url": "https://api.github.com/users/renan/followers",
//   "following_url": "https://api.github.com/users/renan/following{/other_user}",
//   "gists_url": "https://api.github.com/users/renan/gists{/gist_id}",
//   "starred_url": "https://api.github.com/users/renan/starred{/owner}{/repo}",
//   "subscriptions_url": "https://api.github.com/users/renan/subscriptions",
//   "organizations_url": "https://api.github.com/users/renan/orgs",
//   "repos_url": "https://api.github.com/users/renan/repos",
//   "events_url": "https://api.github.com/users/renan/events{/privacy}",
//   "received_events_url": "https://api.github.com/users/renan/received_events",
//   "type": "User",
//   "site_admin": false
// },
// "html_url": "https://github.com/renan/assert",
// "description": "Thin assertion library for use in libraries and business-model",
// "fork": true,
// "url": "https://api.github.com/repos/renan/assert",
// "forks_url": "https://api.github.com/repos/renan/assert/forks",
// "keys_url": "https://api.github.com/repos/renan/assert/keys{/key_id}",
// "collaborators_url": "https://api.github.com/repos/renan/assert/collaborators{/collaborator}",
// "teams_url": "https://api.github.com/repos/renan/assert/teams",
// "hooks_url": "https://api.github.com/repos/renan/assert/hooks",
// "issue_events_url": "https://api.github.com/repos/renan/assert/issues/events{/number}",
// "events_url": "https://api.github.com/repos/renan/assert/events",
// "assignees_url": "https://api.github.com/repos/renan/assert/assignees{/user}",
// "branches_url": "https://api.github.com/repos/renan/assert/branches{/branch}",
// "tags_url": "https://api.github.com/repos/renan/assert/tags",
// "blobs_url": "https://api.github.com/repos/renan/assert/git/blobs{/sha}",
// "git_tags_url": "https://api.github.com/repos/renan/assert/git/tags{/sha}",
// "git_refs_url": "https://api.github.com/repos/renan/assert/git/refs{/sha}",
// "trees_url": "https://api.github.com/repos/renan/assert/git/trees{/sha}",
// "statuses_url": "https://api.github.com/repos/renan/assert/statuses/{sha}",
// "languages_url": "https://api.github.com/repos/renan/assert/languages",
// "stargazers_url": "https://api.github.com/repos/renan/assert/stargazers",
// "contributors_url": "https://api.github.com/repos/renan/assert/contributors",
// "subscribers_url": "https://api.github.com/repos/renan/assert/subscribers",
// "subscription_url": "https://api.github.com/repos/renan/assert/subscription",
// "commits_url": "https://api.github.com/repos/renan/assert/commits{/sha}",
// "git_commits_url": "https://api.github.com/repos/renan/assert/git/commits{/sha}",
// "comments_url": "https://api.github.com/repos/renan/assert/comments{/number}",
// "issue_comment_url": "https://api.github.com/repos/renan/assert/issues/comments{/number}",
// "contents_url": "https://api.github.com/repos/renan/assert/contents/{+path}",
// "compare_url": "https://api.github.com/repos/renan/assert/compare/{base}...{head}",
// "merges_url": "https://api.github.com/repos/renan/assert/merges",
// "archive_url": "https://api.github.com/repos/renan/assert/{archive_format}{/ref}",
// "downloads_url": "https://api.github.com/repos/renan/assert/downloads",
// "issues_url": "https://api.github.com/repos/renan/assert/issues{/number}",
// "pulls_url": "https://api.github.com/repos/renan/assert/pulls{/number}",
// "milestones_url": "https://api.github.com/repos/renan/assert/milestones{/number}",
// "notifications_url": "https://api.github.com/repos/renan/assert/notifications{?since,all,participating}",
// "labels_url": "https://api.github.com/repos/renan/assert/labels{/name}",
// "releases_url": "https://api.github.com/repos/renan/assert/releases{/id}",
// "deployments_url": "https://api.github.com/repos/renan/assert/deployments",
// "created_at": "2014-12-31T12:18:06Z",
// "updated_at": "2014-12-31T12:18:07Z",
// "pushed_at": "2015-03-17T11:53:32Z",
// "git_url": "git://github.com/renan/assert.git",
// "ssh_url": "git@github.com:renan/assert.git",
// "clone_url": "https://github.com/renan/assert.git",
// "svn_url": "https://github.com/renan/assert",
// "homepage": null,
// "size": 249,
// "stargazers_count": 0,
// "watchers_count": 0,
// "language": "PHP",
// "has_issues": false,
// "has_projects": true,
// "has_downloads": true,
// "has_wiki": false,
// "has_pages": false,
// "has_discussions": false,
// "forks_count": 0,
// "mirror_url": null,
// "archived": false,
// "disabled": false,
// "open_issues_count": 0,
// "license": {
//   "key": "other",
//   "name": "Other",
//   "spdx_id": "NOASSERTION",
//   "url": null,
//   "node_id": "MDc6TGljZW5zZTA="
// },
// "allow_forking": true,
// "is_template": false,
// "web_commit_signoff_required": false,
// "topics": [

// ],
// "visibility": "public",
// "forks": 0,
// "open_issues": 0,
// "watchers": 0,
// "default_branch": "master"
